#!/usr/bin/env python

from __future__ import division
from subprocess import Popen, PIPE

import sys

def shell(cmd):
    cmd = cmd.split()
    p = Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE)
    output, err = p.communicate()
    return output

def clean_file(filename):

    filetest = filename.replace(".py", ".test")

    f = open(filename)
    content = ""

    for line in f:

        if "import" in line:
            continue

        line = line.replace('\n', '')
        line = line.split('#')
        content += line[0] + "\n"

    f = open(filetest, 'w')
    f.write(content)
    f.close()

    return filetest

def compare_two(filea, fileb):
    """

    @return number of lines in file A
    @return number of lines in file B
    @return number of git additions
    @return number of git deletions
    """

    # number of lines
    nla = shell("wc -l " + filea)
    nlb = shell("wc -l " + fileb)

    nla = int(nla.split()[0])
    nlb = int(nlb.split()[0])

    git = shell('git diff --numstat --ignore-space-at-eol -b -w --ignore-blank-lines ' + filea + ' ' + fileb)
    git = git.split()

    if len(git) == 0:
        gitadd = 0
        gitdelete = 0
    else:
        gitadd = int(git[0])
        gitdelete = int(git[1])

    return nla, nlb, gitadd, gitdelete


if __name__ == "__main__":

    args = sys.argv[1:]

    filea = args[0]
    fileb = args[1]

    # Clean file of comments and imports
    cleana = clean_file(filea)
    cleanb = clean_file(fileb)

    nla, nlb, ga, gd = compare_two(cleana, cleanb)

    print nla, nlb, ga, gd

    print (ga+gd)/(nla+nlb)

